### ISSUE TITLE
patch/put support

### ISSUE THREAD

**Issue by ericchiang** [ericchiang/k8s#2]
Need to determine if this is any different from JSON patch/put.

**Comment by ewoutp** [comment]
This feature would be really welcome.
As far as I know, a simple PUT should do it (I'm no K8S expert...)

**Comment by ewoutp** [comment]
I'm experimenting with update support (see https://github.com/ewoutp/k8s/tree/update).
The PUT works reasonably well, but the generated types make updating some resources hard.
E.g. since v1.ObjectMeta.DeletionGracePeriodSeconds is not a pointer and not marked `ignoreEmpty`, the K8S complains when I'm trying to update a Deployment with errors like this:

```
metadata.deletionGracePeriodSeconds: Invalid value: 0: field is immutable; may only be changed via deletion
```

Using another protoc generator may solve this, but will change the API.
Suggestions?

**Comment by ewoutp** [comment]
See #7

**Comment by ericchiang** [comment]
Patch support will probably be generated with something similar to:

```
func (c *CoreV1) PatchPod(ctx context.Context, obj *apiv1.Pod, subresource string) (*apiv1.Pod, error)
```

It will be up to the user to known what subresource to specify.

**Comment by ericchiang** [comment]
Sorry, I'm confusing updating a subresource and a patch.

I don't know if we want patch, since it can get pretty hairy. Opened #16 to deal with subresources and closing this.
