### ISSUE TITLE
Any chance we can persuade you to join forces with the main go client?

### ISSUE THREAD

**Issue by lavalamp** [ericchiang/k8s#23]
I hate to see duplication of effort-- what can we do at kubernetes/client-go to get you on board?

**Comment by ericchiang** [comment]
Yeah I'd love to chat with the appropriate sigs about that.

Obviously this client has the huge advantage because it's intentionally solving such a small subset of the client-go functionality. For me, this package feels pretty close to done, and I don't know if I'd want to add dependencies on logging packages or try to support things like the API machinery reflection based tooling in runtime. It would be very hard for this to be the client that kubectl uses.

**Comment by ericchiang** [comment]
Has there ever been a discussion of building a different client for Go users to consume and splitting the dependency the rest of the Kubernetes code base?

**Comment by hsyed** [comment]
Amazing work @ericchiang. The client-go codebase is so tangled with the rest of Kubernetes it cannot be used for making Kubernetes aware microservices. The pod listing hello world is 3.5x smaller than the go-client version !

Please keep working on this clean room implementation !

**Comment by leosunmo** [comment]
I agree with @hsyed! This is immensely helpful when it comes to Kubernetes aware microservices. As a Go novice this package has been amazing. I've created [this small project](https://github.com/leosunmo/jobliterator) using k8s which would have been impossible for me (with my limited Go knowledge) using the "offical" go-client. Please keep this up.

**Comment by ericchiang** [comment]
client-go will have a lot fewer dependencies in the next release.

https://github.com/kubernetes/kubernetes/pull/57059
https://github.com/kubernetes/kubernetes/pull/57259

This client will stick around, but it'd be easy to see a future where client-go is slimmed down enough to be preferred to this one.
