### ISSUE TITLE
Document supported Kubernetes versions/ dependency management

### ISSUE THREAD

**Issue by embano1** [ericchiang/k8s#89]
Thank you Eric for this great and simplified K8s client.

Before digging deeper into it, what is your recommendation for managing dependencies of your k8s when using it in larger Go projects? Also, any support guidelines around which K8s versions are expected to work/not work?

Just want to make sure I get dep management right before falling off at a later stage...

**Comment by ericchiang** [comment]
> Before digging deeper into it, what is your recommendation for managing dependencies of your k8s when using it in larger Go projects?

There's no requirements from this project so use whatever dependency management tool your project already uses. Dep is the community's default choice today, and will likely be replaced by vgo in the future.

https://github.com/golang/dep
https://research.swtch.com/vgo

> Also, any support guidelines around which K8s versions are expected to work/not work?

The intent is to support the lastest version of Kubernetes. The release notes indicate which version is targeted https://github.com/ericchiang/k8s/releases

Hope that helps! Going to close since I believe this answer the questions, but feel free to follow up if you have further questions.

**Comment by embano1** [comment]
Thank you @ericchiang 

The release notes only mention one K8s release, so assuming only the one mentioned in the release note is supported (i.e. no minor skew tested).
